spring.datasource.url=jdbc:postgresql://c4717h2lt37nua.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/dcuf5o6a8qm20v?sslmode=require

spring.datasource.username=u9vn3p2u3erme7
spring.datasource.password=pa23bc72880e52b217b3481b0157bf9c8c4899a3f446908fee8210d8e5c84a024
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=2
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.hibernate.SQL=DEBUG